version: '3'
services:
  db:
    image: "mysql:8.0.19"
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: covidmap
      MYSQL_DATABASE: covidmap
      MYSQL_USER: covid
      MYSQL_PASSWORD: map_password

  web:
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: db
      DATABASE_NAME: covidmap
      DATABASE_USERNAME: covid
      DATABASE_PASSWORD: map_password
      MYSQL_PORT: 33060
      FLASK_RUN_PORT: 8000
  
  # phpmyadmin:
  #   image: "phpmyadmin/phpmyadmin:latest"
volumes:
  db_data: {}